[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/tmp/supervisord.pid
nodaemon=false

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[unix_http_server]
file=/tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:aistore-backend]
command=/usr/local/bin/python -m uvicorn app:app --host 0.0.0.0 --port 8000
directory=/workspaces/AI_Store
autostart=true
autorestart=true
startretries=3
stderr_logfile=/tmp/aistore-backend.err.log
stdout_logfile=/tmp/aistore-backend.out.log
user=vscode

[program:cloudflared]
command=/usr/local/bin/cloudflared tunnel run
environment=TUNNEL_TOKEN="eyJhIjoiMTM2ZWExODUwYzVjM2VlMWM3Yjk4MjllYWQ3Mzg1M2YiLCJ0IjoiZGRkMGQyMGEtNjNlMi00YThlLWExOTItZTdjNDFlMGVmNmIyIiwicyI6Ik1HUTVOalkxTkRjdE5tWTVaaTAwT1RZekxXRTVNRFV0TnpjNU1UZzRaREJoT1RFNCJ9"
autostart=true
autorestart=true
startretries=3
stderr_logfile=/tmp/cloudflared.err.log
stdout_logfile=/tmp/cloudflared.out.log
user=vscode
